In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,test_size=0.2)

In [5]:
lr_score = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=4)
lr_score

array([1.        , 0.94736842, 0.86486486, 1.        ])

In [6]:
svc_score = cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=4)
svc_score

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [7]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators=15),iris.data, iris.target,cv=4)
rf_score

array([0.97368421, 0.94736842, 0.94594595, 1.        ])

In [8]:
np.average(lr_score)

0.9530583214793741

In [9]:
np.average(svc_score)

0.9731507823613088

In [10]:
np.average(rf_score)

0.9667496443812233